package com.qfree.bo.report.db;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;

import com.qfree.bo.report.domain.SelectionListValue;

/**
 * Repository interface for {@link SelectionListValue} persistence.
 *
 * Only query methods that are generated by Spring Data JPA using Spring Data's
 * domain-specific language or via JPQL should be declared here.
 * 
 * @author Jeffrey Zelt
 */
public interface SelectionListValueRepository extends JpaRepository<SelectionListValue, UUID> {
	  
}
