package com.qfree.obo.report.db;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.qfree.obo.report.configuration.Config.ParamName;
import com.qfree.obo.report.domain.Configuration;
import com.qfree.obo.report.domain.Role;

/**
 * Repository interface for {@link Configuration} persistence.
 *
 * Only query methods that are generated by Spring Data JPA using Spring Data's
 * domain-specific language or via JPQL should be declared here.
 * 
 * @author Jeffrey Zelt
 */
public interface ConfigurationRepository extends JpaRepository<Configuration, UUID> {

	@Query("select c from Configuration c where c.paramName=:paramName and c.role=null")
	Configuration findByParamName(@Param("paramName") String paramName);

	@Query("select c from Configuration c where c.paramName=:paramName and c.role=null")
	Configuration findByParamName(@Param("paramName") ParamName paramName);

	//	@Query("select c from Configuration c where c.paramName=:paramName and c.role=:role")
	//	Configuration findByParamName(@Param("paramName") String paramName, @Param("role") Role role);
	@Query("select c from Configuration c where c.paramName=:paramName and c.role=:role")
	Configuration findByParamName(@Param("paramName") ParamName paramName, @Param("role") Role role);

}
