package com.qfree.obo.report.db;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import com.qfree.obo.report.domain.Role;

/**
 * Repository interface for {@link Role} persistence.
 *
 * Only query methods that are generated by Spring Data JPA using Spring Data's
 * domain-specific language or via JPQL should be declared here.
 * 
 * @author Jeffrey Zelt
 */
public interface RoleRepository extends JpaRepository<Role, UUID>, RoleRepositoryCustom {
	  
	//	@NamedQuery(name = "Role.findByUsername", query = "select r from Role r where r.username = ?1")
	@Query("select r from Role r where r.username = :username")
	public Role findByUsername(@Param("username") String username);

}
