package com.qfree.obo.report.db;

import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;

import com.qfree.obo.report.domain.Report;
import com.qfree.obo.report.domain.Role;
import com.qfree.obo.report.domain.RoleReport;

/**
 * Repository interface for {@link RoleReport} persistence.
 *
 * Only query methods that are generated by Spring Data JPA using Spring Data's
 * domain-specific language or via JPQL should be declared here.
 * 
 * @author Jeffrey Zelt
 */
public interface RoleReportRepository extends JpaRepository<RoleReport, UUID> {

	/**
	 * Returns {@link RoleReport} entity given a {@link Role} and a
	 * {@link Report}.
	 * 
	 * @param role
	 * @param report
	 * @return
	 */
	RoleReport findByRoleAndReport(Role role, Report report);

	/**
	 * Same functionality as {@link #findByRoleAndReport(Role, Report)}, but
	 * takes {@link UUID}s as arguments instead of entities.
	 * 
	 * @param roleId
	 * @param reportId
	 * @return
	 */
	/*
	 * The name of this method is odd because it is a Spring Data JPA query
	 * method where the syntax of the method name defines the query that
	 * is performed, as well as the types of the parameters expected.
	 */
	RoleReport findByRoleRoleIdAndReportReportId(UUID roleId, UUID reportId);
	  
}
