package com.qfree.bo.report.db;

import java.util.List;
import java.util.UUID;

import org.springframework.data.jpa.repository.JpaRepository;

import com.qfree.bo.report.domain.JobStatus;

/**
 * Repository interface for {@link JobStatus} persistence.
 *
 * Only query methods that are generated by Spring Data JPA using Spring Data's
 * domain-specific language or via JPQL should be declared here.
 * 
 * @author Jeffrey Zelt
 */
public interface JobStatusRepository extends JpaRepository<JobStatus, UUID> {

	List<JobStatus> findByActiveTrue();

	//	JobStatus findByAbbreviation(String abbreviation);
	//
	//	JobStatus findByDescription(String description);
	//	
	//	List<JobStatus> findByDescriptionLikeOrAbbreviationLike(String description, String abbreviation);
	//
	//	List<JobStatus> findByActiveIsTrue();

}
